// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

pub mod app_bootstrap_init;
pub mod app_lifecycle;
#[path = "navigation/app_nav.rs"]
pub mod app_nav;
#[path = "navigation/app_nav_actions.rs"]
pub mod app_nav_actions;
pub mod app_step1_github_oauth;
pub mod app_step2_log;
pub mod app_step2_router;
pub mod app_step2_saved_log_flow;
pub mod app_step2_scan;
pub mod app_step2_sync_flow;
#[path = "step2/update/app_step2_update_asset_pick.rs"]
pub mod app_step2_update_asset_pick;
#[path = "step2/update/app_step2_update_check.rs"]
pub mod app_step2_update_check;
#[path = "step2/update/app_step2_update_check_worker.rs"]
pub mod app_step2_update_check_worker;
#[path = "step2/update/app_step2_update_download.rs"]
pub mod app_step2_update_download;
#[path = "step2/update/app_step2_update_extract.rs"]
pub mod app_step2_update_extract;
#[path = "step2/update/app_step2_update_github.rs"]
pub mod app_step2_update_github;
#[path = "step2/update/app_step2_update_github_auth.rs"]
pub mod app_step2_update_github_auth;
#[path = "step2/update/app_step2_update_github_forks.rs"]
pub mod app_step2_update_github_forks;
#[path = "step2/update/app_step2_update_github_http.rs"]
pub mod app_step2_update_github_http;
#[path = "step2/update/app_step2_update_github_ref.rs"]
pub mod app_step2_update_github_ref;
#[path = "step2/update/app_step2_update_morpheus_mart.rs"]
pub mod app_step2_update_morpheus_mart;
#[path = "step2/update/app_step2_update_policy.rs"]
pub mod app_step2_update_policy;
#[path = "step2/update/app_step2_update_preview.rs"]
pub mod app_step2_update_preview;
#[path = "step2/update/app_step2_update_source_refs.rs"]
pub mod app_step2_update_source_refs;
#[path = "step2/update/app_step2_update_weaselmods.rs"]
pub mod app_step2_update_weaselmods;
pub mod app_step3_sync_flow;
pub mod app_step4_flow;
pub mod app_step5_flow;
#[path = "navigation/app_update_cycle.rs"]
pub mod app_update_cycle;
#[path = "compat/compat_conflict_parse.rs"]
pub mod compat_conflict_parse;
#[path = "compat/compat_conflict_runtime.rs"]
pub mod compat_conflict_runtime;
#[path = "compat/compat_conflict_scan.rs"]
pub mod compat_conflict_scan;
#[path = "compat/compat_dependency_parse.rs"]
pub mod compat_dependency_parse;
#[path = "compat/compat_dependency_runtime.rs"]
pub mod compat_dependency_runtime;
#[path = "compat/compat_deprecated_scan.rs"]
pub mod compat_deprecated_scan;
#[path = "compat/compat_dlc_source.rs"]
pub mod compat_dlc_source;
#[path = "compat/compat_issue.rs"]
pub mod compat_issue;
#[path = "compat/compat_issue_text.rs"]
pub mod compat_issue_text;
#[path = "compat/compat_logic.rs"]
pub mod compat_logic;
#[path = "compat/compat_mismatch_eval.rs"]
pub mod compat_mismatch_eval;
#[path = "compat/compat_mismatch_scan.rs"]
pub mod compat_mismatch_scan;
#[path = "compat/compat_missing_dep_scan.rs"]
pub mod compat_missing_dep_scan;
#[path = "compat/compat_path_eval.rs"]
pub mod compat_path_eval;
#[path = "compat/compat_path_runtime.rs"]
pub mod compat_path_runtime;
#[path = "compat/compat_path_scan.rs"]
pub mod compat_path_scan;
#[path = "compat/compat_popup_nav.rs"]
pub mod compat_popup_nav;
#[path = "compat/compat_popup_targets.rs"]
pub mod compat_popup_targets;
#[path = "compat/compat_rule_runtime.rs"]
pub mod compat_rule_runtime;
#[path = "compat/compat_rules.rs"]
pub mod compat_rules;
#[path = "compat/compat_rules_model.rs"]
pub mod compat_rules_model;
#[path = "compat/compat_setup_tra.rs"]
pub mod compat_setup_tra;
#[path = "compat/compat_step3_rules.rs"]
pub mod compat_step3_rules;
pub mod component_block_preview;
pub mod component_details;
pub mod controller;
pub mod dispatch;
pub mod eet;
pub mod mod_downloads;
#[path = "step2/update/mod_update_locks.rs"]
pub mod mod_update_locks;
pub mod modlist_config_files;
pub mod modlist_share;
pub mod normal;
#[path = "step2/update/platform_asset_target.rs"]
pub mod platform_asset_target;
pub mod prompt_eval_context;
pub mod prompt_eval_summary;
pub mod prompt_eval_summary_step3;
pub mod prompt_eval_vars;
pub mod prompt_jump_targets;
pub mod prompt_popup_nav;
pub mod prompt_popup_text;
#[path = "step2/scan/mod.rs"]
pub mod scan;
#[path = "step2/scan/scan_components.rs"]
pub mod scan_components;
#[path = "step2/scan/scan_languages.rs"]
pub mod scan_languages;
pub mod selected_details;
pub mod selection_jump;
pub mod selection_refs;
pub mod state;
#[path = "state/state_convert.rs"]
pub mod state_convert;
#[path = "state/state_nav.rs"]
pub mod state_nav;
#[path = "state/state_validation.rs"]
pub mod state_validation;
#[path = "state/state_validation_exec.rs"]
pub mod state_validation_exec;
#[path = "state/state_validation_fs.rs"]
pub mod state_validation_fs;
#[path = "state/state_validation_modes.rs"]
pub mod state_validation_modes;
#[path = "state/step2_action.rs"]
pub mod step2_action;
#[path = "step2/scan/step2_worker.rs"]
pub mod step2_worker;
pub mod step3_history;
pub mod step3_prompt_edit;
pub mod step3_toolbar;
#[path = "state/step4_action.rs"]
pub mod step4_action;
pub mod step4_weidu_log_export;
pub mod step5;
pub mod step5_runtime_status;
pub mod terminal;
