// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ResumeTargets {
    pub bg1_game_dir: Option<String>,
    pub bg2_game_dir: Option<String>,
    pub game_dir: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Step5State<Flag = bool> {
    pub console_output: String,
    pub input_line: String,
    pub hide_top_frames_after_install: Flag,
    pub prep_running: Flag,
    pub install_running: Flag,
    pub last_install_failed: Flag,
    pub last_exit_code: Option<i32>,
    pub last_status_text: String,
    pub install_started_unix_secs: Option<u64>,
    pub last_runtime_secs: Option<u64>,
    pub has_run_once: Flag,
    pub cancel_confirm_open: Flag,
    pub cancel_force_checked: Flag,
    pub cancel_requested: Flag,
    pub cancel_pending: Flag,
    pub cancel_pending_started_unix_secs: Option<u64>,
    pub cancel_pending_output_len: Option<usize>,
    pub cancel_pending_boundary_count: Option<u64>,
    pub cancel_signal_sent_unix_secs: Option<u64>,
    pub cancel_attempt_count: u32,
    pub last_start_mode: String,
    pub last_cancel_mode: String,
    pub restart_program: String,
    pub restart_args: Vec<String>,
    pub resume_targets: ResumeTargets,
    pub diagnostics_run_id: Option<String>,
    pub resolved_bg1_game_dir: String,
    pub resolved_bg2_game_dir: String,
    pub resolved_game_dir: String,
    pub prep_ran: Flag,
    pub prep_used_backup: Flag,
    pub prep_backup_paths: Vec<String>,
    pub prep_cleaned_paths: Vec<String>,
    pub run_counter: usize,
    pub active_run_id: Option<usize>,
    pub resume_available: Flag,
    pub cancel_was_graceful: Flag,
    pub start_install_requested: Flag,
    pub last_auto_prompt_key: Option<String>,
    pub last_scripted_skip_signature: Option<String>,
    pub last_scripted_fallback_signature: Option<String>,
    pub last_scripted_cycle_signature: Option<String>,
    pub last_scripted_send_unix_ms: Option<u64>,
    pub last_scripted_prompt_key: Option<String>,
    pub paused_scripted_component_key: Option<String>,
    pub prompt_ready_signature: Option<String>,
    pub prompt_ready_seen_count: u8,
    pub prompt_ready_first_seen_unix_ms: Option<u64>,
    pub prompt_required_sound_latched: Flag,
    pub prompt_answers_window_open: Flag,
}

impl Default for Step5State {
    fn default() -> Self {
        Self {
            console_output: "Ready.\n".to_string(),
            input_line: String::new(),
            hide_top_frames_after_install: false,
            prep_running: false,
            install_running: false,
            last_install_failed: false,
            last_exit_code: None,
            last_status_text: "Idle".to_string(),
            install_started_unix_secs: None,
            last_runtime_secs: None,
            has_run_once: false,
            cancel_confirm_open: false,
            cancel_force_checked: false,
            cancel_requested: false,
            cancel_pending: false,
            cancel_pending_started_unix_secs: None,
            cancel_pending_output_len: None,
            cancel_pending_boundary_count: None,
            cancel_signal_sent_unix_secs: None,
            cancel_attempt_count: 0,
            last_start_mode: "none".to_string(),
            last_cancel_mode: "none".to_string(),
            restart_program: String::new(),
            restart_args: Vec::new(),
            resume_targets: ResumeTargets::default(),
            diagnostics_run_id: None,
            resolved_bg1_game_dir: String::new(),
            resolved_bg2_game_dir: String::new(),
            resolved_game_dir: String::new(),
            prep_ran: false,
            prep_used_backup: false,
            prep_backup_paths: Vec::new(),
            prep_cleaned_paths: Vec::new(),
            run_counter: 0,
            active_run_id: None,
            resume_available: false,
            cancel_was_graceful: false,
            start_install_requested: false,
            last_auto_prompt_key: None,
            last_scripted_skip_signature: None,
            last_scripted_fallback_signature: None,
            last_scripted_cycle_signature: None,
            last_scripted_send_unix_ms: None,
            last_scripted_prompt_key: None,
            paused_scripted_component_key: None,
            prompt_ready_signature: None,
            prompt_ready_seen_count: 0,
            prompt_ready_first_seen_unix_ms: None,
            prompt_required_sound_latched: false,
            prompt_answers_window_open: false,
        }
    }
}
