// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 Born2BSalty

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Step3ItemState {
    pub tp_file: String,
    pub component_id: String,
    pub mod_name: String,
    pub component_label: String,
    pub raw_line: String,
    pub prompt_summary: Option<String>,
    pub prompt_events: Vec<crate::parser::PromptSummaryEvent>,
    pub selected_order: usize,
    pub block_id: String,
    pub is_parent: bool,
    pub parent_placeholder: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Step3State<Flag = bool> {
    pub active_game_tab: String,
    pub bgee_items: Vec<Step3ItemState>,
    pub bg2ee_items: Vec<Step3ItemState>,
    pub bgee_has_conflict: Flag,
    pub bg2ee_has_conflict: Flag,
    pub bgee_selected: Vec<usize>,
    pub bg2ee_selected: Vec<usize>,
    pub bgee_drag_from: Option<usize>,
    pub bg2ee_drag_from: Option<usize>,
    pub bgee_drag_over: Option<usize>,
    pub bg2ee_drag_over: Option<usize>,
    pub bgee_drag_indices: Vec<usize>,
    pub bg2ee_drag_indices: Vec<usize>,
    pub bgee_anchor: Option<usize>,
    pub bg2ee_anchor: Option<usize>,
    pub bgee_drag_grab_offset: f32,
    pub bg2ee_drag_grab_offset: f32,
    pub bgee_drag_grab_pos_in_block: usize,
    pub bg2ee_drag_grab_pos_in_block: usize,
    pub bgee_drag_row_h: f32,
    pub bg2ee_drag_row_h: f32,
    pub bgee_last_insert_at: Option<usize>,
    pub bg2ee_last_insert_at: Option<usize>,
    pub bgee_collapsed_blocks: Vec<String>,
    pub bg2ee_collapsed_blocks: Vec<String>,
    pub bgee_clone_seq: usize,
    pub bg2ee_clone_seq: usize,
    pub bgee_locked_blocks: Vec<String>,
    pub bg2ee_locked_blocks: Vec<String>,
    pub bgee_undo_stack: Vec<crate::app::step3_history::Step3HistoryEntry>,
    pub bg2ee_undo_stack: Vec<crate::app::step3_history::Step3HistoryEntry>,
    pub bgee_redo_stack: Vec<crate::app::step3_history::Step3HistoryEntry>,
    pub bg2ee_redo_stack: Vec<crate::app::step3_history::Step3HistoryEntry>,
    pub jump_to_selected_requested: Flag,
    pub prompt_edit_open: Flag,
    pub prompt_edit_mode: String,
    pub prompt_edit_key: String,
    pub prompt_edit_component_key: String,
    pub prompt_edit_tp2_file: String,
    pub prompt_edit_component_id: String,
    pub prompt_edit_component_name: String,
    pub prompt_edit_mod_name: String,
    pub prompt_edit_answer: String,
    pub prompt_edit_json: String,
    pub prompt_edit_status: String,
}

impl Default for Step3State {
    fn default() -> Self {
        Self {
            active_game_tab: "BGEE".to_string(),
            bgee_items: Vec::new(),
            bg2ee_items: Vec::new(),
            bgee_has_conflict: false,
            bg2ee_has_conflict: false,
            bgee_selected: Vec::new(),
            bg2ee_selected: Vec::new(),
            bgee_drag_from: None,
            bg2ee_drag_from: None,
            bgee_drag_over: None,
            bg2ee_drag_over: None,
            bgee_drag_indices: Vec::new(),
            bg2ee_drag_indices: Vec::new(),
            bgee_anchor: None,
            bg2ee_anchor: None,
            bgee_drag_grab_offset: 0.0,
            bg2ee_drag_grab_offset: 0.0,
            bgee_drag_grab_pos_in_block: 0,
            bg2ee_drag_grab_pos_in_block: 0,
            bgee_drag_row_h: 0.0,
            bg2ee_drag_row_h: 0.0,
            bgee_last_insert_at: None,
            bg2ee_last_insert_at: None,
            bgee_collapsed_blocks: Vec::new(),
            bg2ee_collapsed_blocks: Vec::new(),
            bgee_clone_seq: 1,
            bg2ee_clone_seq: 1,
            bgee_locked_blocks: Vec::new(),
            bg2ee_locked_blocks: Vec::new(),
            bgee_undo_stack: Vec::new(),
            bg2ee_undo_stack: Vec::new(),
            bgee_redo_stack: Vec::new(),
            bg2ee_redo_stack: Vec::new(),
            jump_to_selected_requested: false,
            prompt_edit_open: false,
            prompt_edit_mode: String::new(),
            prompt_edit_key: String::new(),
            prompt_edit_component_key: String::new(),
            prompt_edit_tp2_file: String::new(),
            prompt_edit_component_id: String::new(),
            prompt_edit_component_name: String::new(),
            prompt_edit_mod_name: String::new(),
            prompt_edit_answer: String::new(),
            prompt_edit_json: String::new(),
            prompt_edit_status: String::new(),
        }
    }
}
